include:
 - board: seeeduino_xiao_ble
   shield: kozakura52_R
   snippet: studio-rpc-usb-uart
 - board: seeeduino_xiao_ble
   shield: kozakura52_L
 - board: seeeduino_xiao_ble
   shield: settings_reset
